global:
  resolve_timeout: 1m
  smtp_smarthost: 'sandbox.smtp.mailtrap.io:587'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: 'c6167e6260562a'
  smtp_auth_password: '9de46057c795f8'
  smtp_auth_identity: 'c6167e6260562a'
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1m
  receiver: 'email'
  
receivers:
- name: 'email'
  email_configs:
  - to: 'EMAIL@gmail.com'
    send_resolved: true
